-   repo: git@github.com:bgschiller/pre-commit-hooks
    sha: 1877870787b800752102ea9262697c81394c79f3
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: flake8
-   repo: git@github.com:asottile/reorder_python_imports
    sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
    hooks:
    -   id: reorder-python-imports
