-   repo: git@github.com:bgschiller/pre-commit-hooks
    sha: 1877870787b800752102ea9262697c81394c79f3
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: flake8
-   repo: git@github.com:asottile/reorder_python_imports
    sha: 9aa4d08f9a28d3defc5e4db3c3b77d1a9980fd1a
    hooks:
    -   id: reorder-python-imports
